In [1]:
# NUMPY ---> Numerical Python
import numpy as np
# numpy provides the support for most powerful data structure -- array
arr = np.array([10,20,30,40,50])
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[10 20 30 40 50]


In [2]:
# List
numbers = [1,2,3,4,5]
total = 0
for n in numbers:
    total +=n
print(total)

15


In [3]:
# Numpy
numbers = np.array([1,2,3,4,5])
print(np.sum(numbers))

15


In [4]:
# how much execution time will it take
import time
numbers = list(range(1, 1000000))
total = 0
start_time = time.time() # record start time
for n in numbers:    
    total += n
end_time = time.time() # record end time
print("Total:", total)
print("Exection Time: ", end_time - start_time, "seconds")
print(f"Execution Time: {end_time - start_time:.4f} seconds") 

Total: 499999500000
Exection Time:  0.47575879096984863 seconds
Execution Time: 0.4758 seconds


In [5]:
# how much execution time will it take (numpy)
numbers = np.arange(1,10000000)
start_time = time.time()
total = np.sum(numbers)
end_time = time.time()
print("Total:", total)
print(f"Execution Time: {end_time - start_time:.4f} seconds") 

Total: 49999995000000
Execution Time: 0.0107 seconds


In [6]:
list1 = [10,"Python",89.21]
print(list1)

[10, 'Python', 89.21]


In [7]:
arr = np.array([10, "Python", 89.21]) #10 and 89.21 will be converted to string because of precedent of data type
print(arr)

['10' 'Python' '89.21']


In [8]:
# Array
# In programming, an array is a data structure used to store a collection of element.
# or values, of the same data type under a single variable name.

# Array: Single Dimensional (1D) and Multi Dimensional (2D)

# How to create a 1D array
# array() used to create 1D or 2D array

arr = np.array([10,20,30,40,50,60])
print(arr)
print(type(arr))

[10 20 30 40 50 60]
<class 'numpy.ndarray'>


In [9]:
# shape property
# used to determine the dimensions of an array
# For 1D array return (n,)  --> where n is the number of elements
# For 2D array return (n,m) --> where n is the number of row and m is the number of column
print(arr.shape)

(6,)


In [10]:
# Create 2D Array
twod = np.array([[1,2], [3,4], [5,6]])
print(twod)
print(twod.shape)

# 3x4
# ([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
# 5x2
# ([[1,2],[3,4],[5,6],[7,8],[9,10]])

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [11]:
arr = np.array([10,20,30,40,50,60,70,80,90])
print(arr)

# Indexing and Slicing
print(arr[2])
print(arr[-1])
print(arr[2:7])
print(arr[::-1])
print(arr[2:7:2])

[10 20 30 40 50 60 70 80 90]
30
90
[30 40 50 60 70]
[90 80 70 60 50 40 30 20 10]
[30 50 70]


In [12]:
twod = np.array([[1,2],[3,4],[5,6]])
print(twod)
print(twod[0,0])  #[row , column]
print(twod[2,1])

# Show me 1st row only
print(twod[0])

# Show me 2nd column 
print(twod[:,1])

# Show me the last row
print(twod[2,:])

print(twod[0:2,:])    #[0:2] --> first two rows



[[1 2]
 [3 4]
 [5 6]]
1
6
[1 2]
[2 4 6]
[5 6]
[[1 2]
 [3 4]]


In [13]:
# Numpy Data Types
arr = np.array([10,20,30,40])
print(arr.dtype) # dtype property helps us to determine the data type of an array

int64


In [14]:
# Memory Optimization
arr = np.array([10,20,30,40])
arr = arr.astype(np.int8) #each element can take up only 8 bits from RAM
print(arr.dtype)

int8


In [15]:
arr = np.array([10.1,20.2,30.3,40.4])
print(arr.dtype) # dtype property helps us to determine the data type of an array

float64


In [16]:
arr = np.array(['apple is nice food','banana','cherry'])
print(arr.dtype) # dtype property helps us to determine the data type of an array

<U18


In [17]:
arr = np.array([True,False,True])
print(arr.dtype) # dtype property helps us to determine the data type of an array

bool


In [18]:
# using dtype for conversion
arr = np.array([1,2,3,4,5],dtype='f4') # 2 bytes --> Bytes into Bits --> 16 [1byte = 8 bits]
print(arr.dtype)

float32


In [19]:
# astype() used for conversion
arr = np.array([1,2,3,4,5])
arr = arr.astype('f8')
print(arr.dtype)

float64


In [20]:
# numpy copy() vs view()
 
# copy()

# a copy will create a new independent array in a different memory location
 
org_arr = np.array([1,2,3,4,5])

copied_arr = org_arr.copy()

print(copied_arr)
 
# if you make changes in copied_arr , it won't affect the original array
 
copied_arr[0] = 100

print(copied_arr)

print(org_arr)
 
# if you make changes in org_arr , it won't affect the copied array
 
org_arr[2] = 300

print(org_arr)

print(copied_arr)
 

[1 2 3 4 5]
[100   2   3   4   5]
[1 2 3 4 5]
[  1   2 300   4   5]
[100   2   3   4   5]


In [21]:
# view()
# a view is the representation of the original array
# it shares the same memory location
 
org_arr = np.array([1,2,3,4,5])
copied_arr = org_arr.view()
print(copied_arr)
 
# if you make changes in copied_arr , it will affect the original array
copied_arr[0] = 100
print(copied_arr)
print(org_arr)
 
# if you make changes in org_arr , it will affect the copied array
 
org_arr[2] = 300
print(org_arr)
print(copied_arr)

[1 2 3 4 5]
[100   2   3   4   5]
[100   2   3   4   5]
[100   2 300   4   5]
[100   2 300   4   5]


In [22]:
org_arr = np.array([1,2,3,4,5])

copied_arr = org_arr.view()
 
# shares_memory() --> returns True if arrays are sharing same memory location
 
print(np.shares_memory(org_arr,copied_arr))
 

True


In [23]:
# Numpy Array Reshaping  --> Converting 1D into 2D  or  2D into 1D
# reshape()
 
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.shape)   # 2x6  6x2  3x4  4x3  12x1  1x12
 
twod = arr.reshape(3,4)
print(twod)

(12,)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [24]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13])   # 1x13  13x1
twod = arr.reshape(13,1)
print(twod)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]]


In [25]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13])
# numpy.newaxis
# is used to increase the dimension of the existing array by one more dimension meaning
# 1D array will become 2D array
arr[:,np.newaxis]  # Column vector

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13]])

In [26]:
# converting 2D into 1D
twod = np.array([[1,2],[3,4],[5,6]])
print(twod.shape)

ar = twod.reshape(6)
print(ar)

(3, 2)
[1 2 3 4 5 6]


In [27]:
twod = np.array([[1,2],[3,4],[5,6]])
print(twod.shape)
ar = twod.reshape(-1)
print(ar)

(3, 2)
[1 2 3 4 5 6]


In [28]:
twod = np.array([[1,2],[3,4],[5,6]])
print(twod.shape)
ar = twod.flatten()
print(ar)

(3, 2)
[1 2 3 4 5 6]


In [29]:
# concatenate()
# used to join 2 arrays

arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6 7 8]


In [30]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8],[9,10]])
arr = np.concatenate((arr1,arr2))
print(arr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [31]:
# array_split()
arr = np.array([1,2,3,4,5,6,7,8,9,10])
np.array_split(arr, 3)

[array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]

In [32]:
# Sorting
# np_sort()  # default ascending order
prices = np.array([78,34,56,90,102,34,12,67,34,120,172,95])
print(np.sort(prices))

[ 12  34  34  34  56  67  78  90  95 102 120 172]


In [33]:
# descending order
prices = np.array([78,34,56,90,102,34,12,67,34,120,172,95])
print(np.sort(prices)[::-1])

[172 120 102  95  90  78  67  56  34  34  34  12]


In [34]:
# Filter in Numpy
arr = np.array([1,4,2,7,9,3,5,8])
print(arr)

# boolean masking
res = arr >= 5
print(res)

# Filter
newarr = arr[arr>=5]
print(newarr)

newarr = arr[arr%2==0]
print(newarr)

[1 4 2 7 9 3 5 8]
[False False False  True  True False  True  True]
[7 9 5 8]
[4 2 8]


In [35]:
# Search in Numpy
# np.where(exprsn)
# np where returns IndexNumbers
arr = np.array([1,4,2,7,9,3,5,8])
res = np.where(arr>= 5)
print(arr[res]) # buat macam ni nak bagi dia tunjuk value dekat IndexNumber tu.

[7 9 5 8]


In [36]:
arr = np.array([10, 32, 30, 50, 20, 82, 91, 45])
 
# Find indices where value is 30
indices = np.where(arr == 30)
print(f"Indices where value is 30: {indices}")
 
# Find indices where values are even
even_indices = np.where(arr % 2 == 0)
print(f"Indices of even values: {even_indices}")
 
# Conditional selection
new_arr = np.where(arr > 40, arr * 2, arr) # kalau nilai lebih daripada 40, darab 2, kalau tak kekalkan nilainya.
print(f"Array after conditional selection: {new_arr}")
 

Indices where value is 30: (array([2]),)
Indices of even values: (array([0, 1, 2, 3, 4, 5]),)
Array after conditional selection: [ 10  32  30 100  20 164 182  90]


In [37]:
# Numpy Random Module
from numpy import random
x = random.randint(100) # 1 until 100
print(x)

34


In [38]:
x = random.randint(100,150) # 100 until 150
print(x)

106


In [39]:
# generate random float
# rand() method returns a random flaot value between 0 and 1
print(random.rand())

0.37563179882689846


In [40]:
# generating random 1D array
x = random.randint(30,70, size=(5))
print(x)

[68 33 64 52 33]


In [41]:
# generating random 2D array
x = random.randint(30,70, size=(3,4))
print(x)

[[46 57 60 61]
 [41 39 65 64]
 [36 66 67 46]]


In [42]:
x = random.randint(100, size=(3,4))
print(x)

[[88 98 21 72]
 [11 37 88 17]
 [23 68 60 16]]


In [43]:
x = random.rand(8)
print(x)

[0.47879505 0.07892188 0.19499611 0.93604385 0.5000903  0.78698244
 0.8197991  0.20288216]


In [44]:
x = random.rand(3,5)
print(x)

[[0.73979387 0.65923583 0.00818302 0.21392812 0.88884433]
 [0.05573285 0.8356369  0.59751393 0.00129424 0.76501923]
 [0.09487592 0.94845661 0.55623684 0.0181911  0.54749693]]


In [45]:
# The choice() method allows you to generate a random value
# based on an array of values.
x = random.choice([3,5,7,9])
print(x)

5


In [46]:
x = random.choice([3,5,7,9],size=12)
print(x)

[5 3 5 7 7 7 9 9 9 7 3 5]


In [47]:
x = random.choice([3,5,7,9],size=(3,4))
print(x)

[[9 3 7 9]
 [9 7 9 5]
 [3 5 5 7]]


In [48]:
# numpy.zeros()
# this function allows us to create an array filled with Zero's 
# default data type will be FLOAT

arr = np.zeros(12)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [49]:
arr = np.zeros((3,5),dtype='i')
print(arr)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [50]:
# numpy.ones()
# this function allows us to create an array filled with One's 
# default data type will be FLOAT

arr = np.ones((3,5),dtype='i')
print(arr)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [51]:
# numpy.sum()
# used to compute the sum of all elements
x = np.random.randint(50,size=(12))
print(x)

[12 39 48 38  8 13 32 39  4 22  9 20]


In [52]:
print(np.sum(x))

284


In [53]:
# numpy.mean()
# mean value is the average value
print(np.mean(x))

23.666666666666668


In [55]:
# numpy.mode()
# the mode value is the value that appears the most
from scipy import stats
print(stats.mode(x))

ModeResult(mode=np.int32(39), count=np.int64(2))


In [56]:
# numpy.unique()
a = np.unique([1,2,3,4,1,2,1,1,1,5,6,7,5,9,10,11,8,6,5])
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11]


In [60]:
arr = np.array([1,2,3,4,1,2,1,1,1,5,6,7,5,9,10,11,8,6,5])

# 1 2 3 4 5 6 7 9 10 11 8

uv , i = np.unique(arr,return_index=True)
 
# return_index=True gives you 2 things

# a.) unique value   -->  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11

# b.) index numbers   --> 0,  1,  2,  3,  9, 10, 11, 16, 13, 14, 15

#     first occurence
 

In [61]:
# argsort --> reorder based on original appearance
uv[np.argsort(i)]

array([ 1,  2,  3,  4,  5,  6,  7,  9, 10, 11,  8])

In [62]:
# arange()
print(np.arange(11))
print(np.arange(1,11))
print(np.arange(1,11,3))


[ 0  1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  4  7 10]


In [66]:
print(np.arange(4).reshape(2,2))

[[0 1]
 [2 3]]


In [68]:
# numpy broadcasting
arr1 = np.array([4,5,7,8])
arr2 = np.array([8,1,3,4])
print(arr1 + arr2)

[12  6 10 12]


In [69]:
# if we try to perform arithmetic operation 
# b/w uncompatible shapes
 
arr1 = np.array([4,5,7,8])
arr2 = np.array([8,1,3])
print(arr1 + arr2)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [70]:
# if any one of them is 1
 
arr1 = np.array([4,5,7,8])
arr2 = np.array([8])
print(arr1 + arr2)

[12 13 15 16]


In [ ]:
# Website to see the documentation of numy: https://numpy.org/doc/stable/user/absolute_beginners.html